# Generated by Django 3.1.6 on 2021-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Background', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
