# Generated by Django 3.1.6 on 2021-03-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_movie_movie_id'),
        ('MovieGenres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='movie_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.movie'),
        ),
    ]
