# Generated by Django 3.1.6 on 2021-03-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_title', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
