# Generated by Django 3.1.6 on 2021-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
