# Generated by Django 3.1.7 on 2021-03-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_recent_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
