# Generated by Django 3.1.7 on 2021-04-01 02:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/blank_avatar.png', null=True, upload_to=accounts.models.upload_image_path),
        ),
    ]
