# Generated by Django 3.1.6 on 2021-03-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('birthYear', models.CharField(blank=True, max_length=120, null=True)),
                ('DeathYear', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
