# Generated by Django 3.1.6 on 2021-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
