# Generated by Django 3.1.6 on 2021-03-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
        ('Person', '0002_personjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='personjob',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.job'),
        ),
    ]
