# Generated by Django 3.1.6 on 2021-03-26 00:32

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20210323_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Movies.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
