# Generated by Django 3.1.6 on 2021-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20210311_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
