# Generated by Django 3.1.6 on 2021-03-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_moviegenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre_id',
        ),
    ]
