# Generated by Django 3.1.6 on 2021-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_auto_20210325_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='temp_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
