# Generated by Django 3.1.6 on 2021-03-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0001_initial'),
        ('Movies', '0005_remove_moviegenre_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='genre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Genres.genre'),
        ),
    ]
