# Generated by Django 3.1.6 on 2021-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20210327_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
