# Generated by Django 3.1.6 on 2021-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_auto_20210327_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
