# Generated by Django 3.1.6 on 2021-03-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('Movies', '0007_movieemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieemployee',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.person'),
        ),
    ]
