# Generated by Django 3.1.6 on 2021-03-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_personjob_job_id'),
        ('Movies', '0008_auto_20210311_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieEmployee',
            new_name='MoviePerson',
        ),
    ]
